#!/usr/bin/env python3
"""
Generate paper-ready tables + a combined figure for the DPE experiment.

Aggregates every per-model comparison in a DPE run directory into:
  1. dpe_results_table.tex   — LaTeX table: disparity reduction + effect sizes
                                + a RESPONSE-COHERENCE sanity column (avg length,
                                % empty) so degenerate output can't hide.
  2. dpe_combined_figure.pdf — grouped bar chart of disparity reduction per model.
  3. dpe_aggregate_summary.json — machine-readable roll-up.

Usage
-----
python scripts/generate_dpe_paper_tables.py \
    --dpe-run-dir results/dpe_20260714_121248 \
    --baseline-dir results/single_runs_35k \
    --out-dir results/dpe_paper_assets

The run dir is expected to contain, per model:
    <model>_dpe.db
    compare_<model>/dpe_comparison_summary.json
"""

from __future__ import annotations

import argparse
import glob
import json
import re
import sqlite3
import sys
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

MODEL_DISPLAY = {
    "llava": "LLaVA-v1.6-7B",
    "internvl2": "InternVL2-2B",
    "idefics2": "IDEFICS2-8B",
    "llama": "Llama-3.2-11B",
}


def _pretty_model(raw: str) -> str:
    low = raw.lower()
    for key, disp in MODEL_DISPLAY.items():
        if key in low:
            return disp
    return raw


# ---------------------------------------------------------------------------
# Coherence sanity — did DPE keep responses intelligible?
# ---------------------------------------------------------------------------

def response_coherence(db_path: str) -> Dict[str, float]:
    """Avg response length (chars), % empty, and distinct-response ratio."""
    if not Path(db_path).exists():
        return {}
    conn = sqlite3.connect(db_path)
    try:
        rows = conn.execute(
            "SELECT response FROM probe_results WHERE response IS NOT NULL"
        ).fetchall()
    except sqlite3.OperationalError:
        conn.close()
        return {}
    conn.close()

    if not rows:
        return {}
    lengths = [len((r[0] or "").strip()) for r in rows]
    n = len(lengths)
    n_empty = sum(1 for L in lengths if L == 0)
    n_veryshort = sum(1 for L in lengths if L < 3)
    distinct = len({(r[0] or "").strip() for r in rows})
    return {
        "n": n,
        "avg_len": float(np.mean(lengths)),
        "pct_empty": 100.0 * n_empty / n,
        "pct_veryshort": 100.0 * n_veryshort / n,
        "distinct_ratio": distinct / n,
    }


# ---------------------------------------------------------------------------
# Load per-model comparison summaries
# ---------------------------------------------------------------------------

def load_model_results(dpe_run_dir: Path, baseline_dir: Path) -> List[dict]:
    results = []
    for cmp_dir in sorted(dpe_run_dir.glob("compare_*")):
        summary_path = cmp_dir / "dpe_comparison_summary.json"
        if not summary_path.exists():
            continue
        with open(summary_path) as f:
            summary = json.load(f)

        raw_name = cmp_dir.name.replace("compare_", "")
        # DPE db lives in the run dir; baseline db in baseline_dir (best match)
        dpe_db = next(iter(dpe_run_dir.glob(f"{raw_name}*_dpe.db")), None)
        dpe_db = str(dpe_db) if dpe_db else ""

        coh_dpe = response_coherence(dpe_db) if dpe_db else {}

        results.append({
            "raw_name": raw_name,
            "display": _pretty_model(raw_name),
            "summary": summary,
            "coherence_dpe": coh_dpe,
        })
    return results


# ---------------------------------------------------------------------------
# LaTeX table
# ---------------------------------------------------------------------------

def build_latex_table(results: List[dict]) -> str:
    lines = [
        r"% Auto-generated by generate_dpe_paper_tables.py",
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\caption{\textbf{Demographic Positional Encoding reduces measured "
        r"disparity.} Per-model valence disparity ($\sigma$, std of per-group "
        r"means) before (Base) and after DPE, with relative reduction. "
        r"Coherence columns confirm DPE preserves intelligible output "
        r"(avg.\ response length in characters; \% empty responses).}",
        r"\label{tab:dpe_results}",
        r"\small",
        r"\begin{tabular}{lcccccccc}",
        r"\toprule",
        r"& \multicolumn{3}{c}{\textbf{Gender } $\sigma\!\downarrow$} "
        r"& \multicolumn{3}{c}{\textbf{Region } $\sigma\!\downarrow$} "
        r"& \multicolumn{2}{c}{\textbf{Coherence}} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-9}",
        r"\textbf{Model} & Base & DPE & Red.\% & Base & DPE & Red.\% "
        r"& Len & \%Emp \\",
        r"\midrule",
    ]

    for r in results:
        disp = r["summary"].get("disparity", {})
        g = disp.get("gender_presentation", {})
        reg = disp.get("jurisdiction_region", {})
        coh = r["coherence_dpe"]

        def fmt(x, nd=4):
            return f"{x:.{nd}f}" if isinstance(x, (int, float)) else "--"

        def pct(x):
            return f"{x:+.1f}" if isinstance(x, (int, float)) else "--"

        row = (
            f"\\model{{{r['display']}}} "
            f"& {fmt(g.get('baseline'))} & {fmt(g.get('dpe'))} & {pct(g.get('pct_reduction'))} "
            f"& {fmt(reg.get('baseline'))} & {fmt(reg.get('dpe'))} & {pct(reg.get('pct_reduction'))} "
            f"& {fmt(coh.get('avg_len'), 0) if coh else '--'} "
            f"& {fmt(coh.get('pct_empty'), 1) if coh else '--'} \\\\"
        )
        lines.append(row)

    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Combined figure
# ---------------------------------------------------------------------------

def build_combined_figure(results: List[dict], out_path: Path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({"font.family": "serif", "font.size": 10})

    models = [r["display"] for r in results]
    gender_red = [r["summary"].get("disparity", {})
                  .get("gender_presentation", {}).get("pct_reduction", np.nan)
                  for r in results]
    region_red = [r["summary"].get("disparity", {})
                  .get("jurisdiction_region", {}).get("pct_reduction", np.nan)
                  for r in results]

    x = np.arange(len(models))
    width = 0.38
    fig, ax = plt.subplots(figsize=(max(5, len(models) * 2), 4))
    ax.bar(x - width / 2, gender_red, width, label="Gender", color="#3498db")
    ax.bar(x + width / 2, region_red, width, label="Region", color="#e67e22")
    ax.axhline(0, color="black", linewidth=0.7)
    ax.set_xticks(x)
    ax.set_xticklabels(models, rotation=15, ha="right")
    ax.set_ylabel("Valence disparity reduction (%)")
    ax.set_title("DPE: demographic disparity reduction by model")
    ax.legend()

    for xi, (gv, rv) in enumerate(zip(gender_red, region_red)):
        if not np.isnan(gv):
            ax.text(xi - width / 2, gv, f"{gv:.0f}%", ha="center",
                    va="bottom" if gv >= 0 else "top", fontsize=8)
        if not np.isnan(rv):
            ax.text(xi + width / 2, rv, f"{rv:.0f}%", ha="center",
                    va="bottom" if rv >= 0 else "top", fontsize=8)

    plt.tight_layout()
    plt.savefig(out_path, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dpe-run-dir", required=True,
                        help="A results/dpe_<timestamp> directory.")
    parser.add_argument("--baseline-dir", default="results/single_runs_35k",
                        help="Directory holding baseline DBs (for coherence ref).")
    parser.add_argument("--out-dir", default=None,
                        help="Where to write assets (default: <dpe-run-dir>/paper_assets).")
    args = parser.parse_args()

    dpe_run_dir = Path(args.dpe_run_dir)
    baseline_dir = Path(args.baseline_dir)
    out_dir = Path(args.out_dir) if args.out_dir else dpe_run_dir / "paper_assets"
    out_dir.mkdir(parents=True, exist_ok=True)

    results = load_model_results(dpe_run_dir, baseline_dir)
    if not results:
        print(f"ERROR: no compare_*/dpe_comparison_summary.json found in {dpe_run_dir}")
        sys.exit(1)

    print(f"Loaded {len(results)} model comparison(s): "
          f"{', '.join(r['display'] for r in results)}")

    # Coherence sanity warnings
    for r in results:
        coh = r["coherence_dpe"]
        if coh and (coh.get("pct_empty", 0) > 10 or coh.get("avg_len", 99) < 5):
            print(f"  ⚠ {r['display']}: DPE output looks degenerate "
                  f"(avg_len={coh.get('avg_len'):.1f}, %empty={coh.get('pct_empty'):.1f}) "
                  f"— check alpha is not too high.")

    # LaTeX table
    tex = build_latex_table(results)
    tex_path = out_dir / "dpe_results_table.tex"
    tex_path.write_text(tex)
    print(f"  Wrote {tex_path}")

    # Combined figure
    fig_path = out_dir / "dpe_combined_figure.pdf"
    build_combined_figure(results, fig_path)
    print(f"  Wrote {fig_path}")

    # Aggregate JSON
    agg = {
        r["display"]: {
            "disparity": r["summary"].get("disparity", {}),
            "overall": r["summary"].get("overall", {}),
            "coherence_dpe": r["coherence_dpe"],
        }
        for r in results
    }
    agg_path = out_dir / "dpe_aggregate_summary.json"
    agg_path.write_text(json.dumps(agg, indent=2))
    print(f"  Wrote {agg_path}")

    print(f"\n✓ Paper assets in {out_dir}")


if __name__ == "__main__":
    main()
